local: &local
  adapter: mysql2
  encoding: utf8
  host: localhost
  username: postgres
  password: password
  pool: 5

development:
  <<: *local
  database: lott-reps_development

production:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
