source 'https://rubygems.org'

ruby '2.0.0'

# Rails 4 plugins 
gem 'rails_12factor'
gem 'actionpack-action_caching', github: 'rails/actionpack-action_caching'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.1'

# Use postgres as the database for Active Record
gem 'pg'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.0'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'

# Use jquery as the JavaScript library
gem 'jquery-rails'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

# Form Helper
gem 'simple_form'

# DataTables
gem 'jquery-datatables-rails', github: 'rweng/jquery-datatables-rails'
# Pagination
gem 'will_paginate'

# For growl style flash messages
gem "gritter", "1.0.3"

# Front-end Framework
gem 'zurb-foundation'

gem  'rest-client'
gem  'json'
gem  'rubyzip'
gem  'aws-s3'
